# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: debian:stable

stages:
  - build1
  - build2
  - build3

before_script:
  - apt-get update -qq
  - cd /builds/fischertechnik/FT-TXT
  - ./Linux-Pakete-Required.sh
  - env DEBIAN_FRONTEND=noninteractive  ./Linux-Pakete-Extra.sh
  - apt-get -y install joe git gitk cvs wget cpio

after_script:
  - echo "END"

Make-TXT-Bootloader:
  stage: build1
  script:
    - mkdir /opt/FT
    - chmod a+rw /opt/FT
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-Bootloader.sh > Make-TXT-Bootloader.sh.log
  artifacts:
    paths:
    - /builds/fischertechnik/u-boot
    expire_in: 1 week
  after_script:
    - ls -la /builds/fischertechnik/u-boot
    
Make-TXT-Buildroot-Clean:
  stage: build2
  script:
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-Buildroot-Clean.sh > Make-TXT-Buildroot-Clean.sh.log
  artifacts:
    paths:
    - /builds/fischertechnik/buildroot
    expire_in: 1 week
  after_script:
    - ls -la /builds/fischertechnik/buildroot
    
Make-TXT-Image:
  stage: build3
  script:
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-Image.sh
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
    - /builds/fischertechnik
    - /builds/fischertechnik/ft-TXT_Build_$BUILD.img.zip
    expire_in: 1 week
  after_script:
    - ls -la /builds/fischertechnik
    - export BUILD=`cat /builds/fischertechnik/FT-TXT/board/FT/TXT/BUILD`

Make-TXT-UpdateScripts:
  stage: build3
  script:
    - mkdir /builds/fischertechnik/update
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-UpdateScripts.sh
  artifacts:
    name: "update.sh"
    paths:
      - /builds/fischertechnik/update
      - /builds/fischertechnik/update/update.sh
    expire_in: 1 week
  after_script:
    - ls -la /builds/fischertechnik/update

Make-TXT-Graphs:
  stage: build3
  before_script:
    - apt-get -y install graphviz python-matplotlib python-numpy # make graph-*
  script:
    - cd /builds/fischertechnik/buildroot
    - make graph-depends
    - make graph-build
    - make graph-size
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - /builds/fischertechnik/buildroot/output/graphs
  after_script:
    - ls -la /builds/fischertechnik/buildroot/output/graphs
