# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: debian:stable

stages:
  - build1
  - copy1
  - build2
  - copy2
  - build3

before_script:
  - apt-get update -qq
  - cd /builds/fischertechnik/FT-TXT
  - ./Linux-Pakete-Required.sh
  - env DEBIAN_FRONTEND=noninteractive  ./Linux-Pakete-Extra.sh
  - apt-get -y install joe git gitk cvs wget cpio -qq

after_script:
  - echo "END"

make:bootloader:
  stage: build1
  script:
    - mkdir /opt/FT
    - chmod a+rw /opt/FT
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-Bootloader.sh #> Make-TXT-Bootloader.sh.log

copy:bootloader:
  stage: copy1
  script:
    - cp -R /builds/fischertechnik/u-boot/ "$CI_PROJECT_DIR/u-boot/"
  artifacts:
    name: "$CI_COMMIT_REF_NAME-bootloader"
    paths:
    - "$CI_PROJECT_DIR/u-boot/"
    expire_in: 1 week
  after_script:
    - ls -la "$CI_PROJECT_DIR/u-boot/"
    
make:buildroot:
  stage: build2
  script:
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-Buildroot-Clean.sh > Make-TXT-Buildroot-Clean.sh.log

copy:bootloader:
  stage: copy2
  script:
    - cp -R /builds/fischertechnik/buildroot/ "$CI_PROJECT_DIR/buildroot/"
  artifacts:
    name: "$CI_COMMIT_REF_NAME-buildroot"
    paths:
    - "$CI_PROJECT_DIR/buildroot/"
    expire_in: 1 week
  after_script:
    - ls -la "$CI_PROJECT_DIR/buildroot/"

make:image:
  stage: build3
  script:
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-Image.sh
    - export BUILD=`cat /builds/fischertechnik/FT-TXT/board/FT/TXT/BUILD`
    - cp "/builds/fischertechnik/ft-TXT_Build_$BUILD.img.zip" "$CI_PROJECT_DIR/ft-TXT_Build_$BUILD.img.zip"
  artifacts:
    name: "$CI_COMMIT_REF_NAME-image"
    paths:
    - "$CI_PROJECT_DIR/ft-TXT_Build_$BUILD.img.zip"
    expire_in: 1 week
  after_script:
    - ls -la "$CI_PROJECT_DIR/ft-TXT_Build_$BUILD.img.zip"

make:update:
  stage: build3
  script:
    - mkdir /builds/fischertechnik/update
    - cd /builds/fischertechnik/FT-TXT
    - ./Make-TXT-UpdateScripts.sh
    - cp -R /builds/fischertechnik/update/ "$CI_PROJECT_DIR/update/"
  artifacts:
    name: "$CI_COMMIT_REF_NAME-update"
    paths:
      - "$CI_PROJECT_DIR/update/"
    expire_in: 1 week
  after_script:
    - ls -la "$CI_PROJECT_DIR/update/"

make:graphs:
  stage: build3
  before_script:
    - apt-get -y install graphviz python-matplotlib python-numpy -qq
  script:
    - cd /builds/fischertechnik/buildroot
    - make graph-depends
    - make graph-build
    - make graph-size
    - cp -R /builds/fischertechnik/buildroot/output/graphs/ "$CI_PROJECT_DIR/graphs/"
  artifacts:
    name: "$CI_COMMIT_REF_NAME-graphs"
    paths:
      - "$CI_PROJECT_DIR/graphs/"
  after_script:
    - ls -la "$CI_PROJECT_DIR/graphs/"
