# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: debian:stable

before_script:
  - cd /builds/fischertechnik/FT-TXT
  - ./Linux-Pakete-Required.sh

#after_script:
#  - echo "After script section"
#  - echo "For example you might do some cleanup here"
   
build1:
  stage: build
  script:
    - ./Make-TXT-Bootloader.sh
    - ./Make-TXT-Buildroot-Clean.sh
   
#test1:
#  stage: test
#  script: 
#    - echo "Do a test here"
#    - echo "For example run a test suite"
   
#test2:
#  stage: test
#  script: 
#    - echo "Do another parallel test here"
#    - echo "For example run a lint test"
   
#deploy1:
#  stage: deploy
#  script:
#    - echo "Do your deploy here"
